### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by studentEEC** [3DLeapScanner/LeapScanner#2]
Hello I was trying open this project. I have an leap motion, visual studio 2017 and all the libraries installed in my computer, however the version of libraries and visual studio aren't the same that you have.
I cannot run the project. 

You can help me? Please...

**Comment by sattar92** [comment]
Yes I can help you. kindly explain what you are intended to do ...

**Comment by sattar92** [comment]
Yes I can help you ... kindly state detail of your intentions
